version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - type: bind
        source: ./backend
        target: /code/backend_app
    ports:
      - "8080:80"
    depends_on:
      - database
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - type: bind
        source: ./frontend/src
        target: /app/src
      - type: bind
        source: ./frontend/index.html
        target: /app/index.html
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - database
  database:
    image: mysql:latest
    volumes:
      - type: bind
        source: ./docker/database/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=secure-password123456
    ports:
      - "3306:3306"