version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - type: bind
        source: ./backend
        target: /code/backend
    networks:
      main:
       ipv4_address: 10.105.10.2
    ports:
      - "8080:80"
    depends_on:
      - database
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - type: bind
        source: ./frontend/src
        target: /app/src
      - type: bind
        source: ./frontend/index.html
        target: /app/index.html
    ports:
      - "8181:5173"
    depends_on:
      - backend
      - database
  database:
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    volumes:
      - type: bind
        source: ./docker/database/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=secure-password123456
    networks:
      main:
        ipv4_address: 10.105.10.3
    ports:
      - "3306:3306"


networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 10.105.10.0/24
          gateway: 10.105.10.1